### ISSUE TITLE
Milestone 1: Architecture design and implementation

### ISSUE THREAD

**Issue by rkkoszewski** [sweat-tek/WUI#1]
- [x] Decide on programming pattern (Probably reactive)
- [x] Decide on the architecture, namespacing and so forth regarding the Classpath and Organization of the application. 
- [x] Decide which web server framework to use and how to implement its integration.
- [x] Decide on where the application entry point is, and how the UI system gets initialized (Example: JavaFX has a custom “main” function that is executed in the JavaFX context, or another approach would be to be able to access and modify the UI from outside directly from Java’s main. (Decide)
- [x] Decide upon what dependency management solution to use (Like Maven, but still be OSGi compatible, and so on) -> Maven
- [x] Decide how to define a new UI Element, and implement the base UI Element class which will be inherited by all the child elements.
- [x] Decide how UI Elements data will be synchronized between the Class and the Visual counterpart. Also figure out how to tackle UI Elements vs UI Element Positioning, and how to synchronize this also.
- [x] Implement a simple but working MVP which would allow a user to design a simple hello world UI and interact with it by clicking a button. (No web-sockets, just simple periodic AJAX calls)
- [ ] Decide and design the UI Engine’s architecture, the engine that manages and links the Java UI Class elements to its Web Counterpart.
- [ ] Decide how a View is defined, and how the user can add elements to that view. (Also, different types of view like “static”, “per-session-dynamic”.

**Comment by rkkoszewski** [comment]
Regarding the Architecture and project organisation: From the current status of the requirements, the project will consist of 3 basic parts (Core Engine, Server and Renderer) and one extra example module that would show different examples on how to use WUI.

From the 3 basic modules:
- Core Engine: Includes the whole API and the logic of the engine.
- Server: This implements the Server API, that allows to serve the UI resources trough the HTTP and Socket protocol. This is shipped as an external module, to allow to swap implementations. The initial implementation will be "nanohttpd" based, which should have a small runtime fingerprint due to it's tiny implementation. In the future another implementation using Jetty may be done too, and may be used to do speed tests.
- Renderer: Implements the Renderer API, and is basically what launches the Browser interface. A basic "just open the browser" render may be included in the "Core Engine", but further renderers like Java's JavaFX and JXBrowser will be shipped as separate modules (This is due to dependencies, having JavaFX forces a dependency on Java 8 of the whole projects, externalizing this into its own module avoids this, and allows to choose alternative renderers if Java 8 is not available in the target infrastructure)

The project structure should be as follows:

/ - Root Core Initiator (Window?)
/elements - Widgets
/server - Server Engines API	
/renderer - Browsers API
/templates
/utils
	/structs
	/net
	/string
	/info
	/reflection
	
	
-------------
/example - Example Window
	/controller
	/view
	/model
	
-------------
/server - Server Engines	
	
-------------
/renderer - Browsers
	
Still TO DO (Decide):
Configuring the WUI Environment
	1. - Trough Environment Properties
	2. - Directly from the Engine (Allowing the developer to set settings)

**Comment by rkkoszewski** [comment]
**Programming Pattern (Architecture Related):**
The final decision is to support several programming patterns as described next:

1. **Annotation Based**: The views are declared by using annotations. Instead of programatically registering every view, the developer will have to specify the Classpath that should be used to scan for annotations.
2. **Interface Based:** In this way the programmer implements the View interface and implements its methods. This resulting class can be registered to the view programatically .
3. **Sequentially Defined**: In this way the developer can initialise a view and define its contents in a sequential way, similar on how Java Swing Windows are defined.

_For the first milestone only the Interface based approach will be implemented._

**Comment by rkkoszewski** [comment]
**Web Server Framework:**
The Web Server is required to support HTTP, as also be able to work with WebSockets to support the full required feature set.

There are many available solutions. From what I could find out **Jetty** and **Netty** are the most used servers, but are a pretty huge framework. As this project is aiming to be as lightweight as possible I will use **NanoHTTPD** which is very lightweight to implement the server part (Altough it may be less stable than a Netty implementation). But as WUI will support swappable Server implementation, it is to see in the future if an alternative Jetty or Netty implementation will be performed (May be used to speed and memory usage comparisons later on).

**Comment by rkkoszewski** [comment]
**Framework Usage Workflow:**
1. The framework Window has to be initialised and a page template has to be specified. (Configurations can be performed here too) [Behind the scenes here the Server will be chosen and initialized]
2. All required views are added to the Window together with an URI (Right now it is absolute, but a more dynamic routing will be researched later on). [How Views are defined is explained in section Programming Pattern (Architecture Related)]
3. A (browser) Renderer has to be picked and will display the root URI. 
4. The program is terminated when the System.exit method is called.

**About the Template:**
The Template can be seen as a pre-made design of a page/window/view. By default (also known as the "Base" template") an empty canvas will be shown and allows to add the different elements to it all starting from the root node (Whole page). More functional Templates can also be defined in WUI, where instead of having a blank canvas, we can have an existing layout with a sidebar menu, a toolbar and the content pane, which can all be accessed from the _Template_ class. Any Template implements the _Template_ interface which include the base capabilities a Template requires to implement. Additional capabilities can be specified by adding more Capability-Interfaces like example: _SidebarMenu_, _Toolbar_, etc. This will allow a View to dynamically check if the current Template supports each element and react depending on the available capabilities (This check can be easily done by using the _instanceof_ evaluator in Java).

**Comment by rkkoszewski** [comment]
**Base Template - Web Resources (Rendered resources):** 
In order for WUI to work in a Browser (Renderer) a the system that synchronizes and generates the DOM elements has to be implemented in Javascript (**This engine will be called _WUIJS_ from now on**). 

**Browser side workflow (WUIJS):**
This worflow starts right after what has been explained in section Framework Usage Workflow in the bullet point 3. When the browser/renderer is opened.

1. Once the Browser/Renderer has started, it will proceed to load the desired URL. No matter what URL is being loaded, the Server will always return the Template, the template includes the WUIJS script which when started starts the whole UI and Synchronization logic and also loads all required Element definitions.
2. WUIJS will look at the current URL and make a request to the server to get the View information (Special Headers will be used here to differentiate calls)
3. Once WUIJS gets the View data, it will proceed to generate the required DOM from the Element definitions, update and transform each element as required.

**How Elements are Defined and Extended:**
.. WORKING ON IT ..

**Comment by rkkoszewski** [comment]
**First design on how Elements are defined and extended:**
First we need in the Java side the definition of the Element Class. One of it's methods will be to get the HTML definition, initializers, data setters and so on. This will be defined in a easy to use XML based html file (This will be called **ElementDefinition** file). 

**Extending Existing Elements:**
The Content Manager will have a Element extension method, which will allow the template to override templates from existing classes, overriding in fact only the HTML and Javascript definitions of the Class.
This will be achieved by the Override pool, which will be basically a HashMap containing the Full Path to the Overriden Element, and the new _ElementDefinition_ file.

**Stuff still to be considered:**
Some elements may require other external dependencies like 3rd party libraries (This will have to be defined somewhere, probably in the ElementDefinition file). Some elements may clash with different versions of the same 3rd party library. This is something that will have to be sorted out.

**Comment by rkkoszewski** [comment]
**WUI.CORE.JS: DOM Building, Element definition, nesting and synchronization:**
General Workflow of WUI.CORE.JS Version 1.

0. When the user first opens a page, the template gets shown and the WUI.CORE.JS file loaded.
1. WUI.CORE.JS checks the current URL and sends a AJAX request to the server to the same URL but with the "x-wui-request:content" header set. The server will respond with the CONTENT definition based on nested NODEs (The structure of wich can be seen in the CONTENT and NODE section).
2. This call will be performed every second till the user changes the view. Every next call performed will include the last CONTENT timestamp. There are 4 possible responses that can be received here:

- **Empty Response**: This means that the content has not changed. 
- **Partial DOM Change Response**: In this response only the DOM elements are sent, but not it's data. Any DOM element that does not appear, will be removed from the browser DOM. Any moved element, will be recognized as moved and moved in the browser DOM.
- **Partial Data Change Response**: In this case the Element nesting positions haven't changed, but only the Element's data. In this case an array of Elements with its UUIDs and DATA is sent, and updates are performed in the browser side.
- **Partial Data change with DOM Change Response**: In the case the Elements changed position and some of it's data changed too, a similar response to the "Partial DOM Change Response" is received, but the Elements who's data has changed will have the "data" filled, otherwise left out. 

**CONTENT:**
```
{
	"title": "Page Title",
	"nodes": {
		"body": [NODE, ...]
	}, 
	"timestamp": "1231243"
}
```

**NODE:**
```
{
	"element": "Element.Type", --> Element Class or Type Identifier
	"timestamp": "1234", --> By now skipped. When the element was last updated.
	"uuid": "123-asd-53", --> Unique Element Identifier
	"data" : {}, --> The Element's Data
	"nodes": { --> The Element's Child Nodes (When available)
		"id_1": [NODE, NODE, NODE], --> Multiple Child Slots may be available.
		"id_2": [NODE, NODE, NODE]  --> Therefore we use ID's to identify them.
	}
}
```

**Synchronization Strategy:** 
As of now the synchronization is timestamp-based for all elements and nesting. Because of this approach removing an element can become memory intensive, as every removed element at some time will have to be notified as deleted to the client. To avoid this, every time the Element nesting changes the whole DOM nesting will be sent to the client. Any Element that is in the client's DOM but not in the response, will be assumed to have been deleted. This way the tradeoff is to have a higher bandwith usage during nesting changes, but avoids explicit deletion notifications and also makes the system more error resistant during bogus synchronizations (Which should not happen, but should always be expected).

**Comment by rkkoszewski** [comment]
**Decision to move the project from Java 7 to Java 8:**
WUI is aimed to be used by an as big as possible audience. One important and potentially limiting part is the availability of the latest JVM, and especially in strict Enterprise environments upgrading the JVM can prove to be tricky and very slow. A few years ago Java 7 was considered the most available Java platform on the client ecosystem, but now with the officially stable release of Java 9, the move to use Java 8 seems a logical step. Java 8 includes new and very powerful features, being the most prominent ones the availability of JavaFX, Lambda functions and Default functions in Interfaces, which will be of great benefit for the project.

**Comment by rkkoszewski** [comment]
**New Lock Based Updates:**
In order to prepare the framework to be WebSocket compatible, some internal changes had to be done to the general working flow. Now instead of periodically calling viewUpdate() on every request, an inverted approach has been taken, where the client connects to the server, and the connection is kept stalled unless updated content is available (Also known as Comet technique). This on one side can result in a much lower bandwidth usage when not much content is updated, as also the time till updated content is displayed on the client side is drastically decreased too (From over 1 second to around 120 ms). The "downside" to this is that there is higher data throughput, elements can be updated much quicker, and as such more bandwidth will be used which may hurt mobile data. But to further optimise this case the next update strategies have been developed.

**Update Strategies:**
Whenever an element is updated in a view, the data is sent to the client. It may happen that when several elements get updated, the updates may split and get sent in different requests with each request coming with its extra overhead. So basically two update strategies will be implemented to the system:
- **DEFAULT Update All**: This is the default behaviour, whenever any of the elements is updated, the data will be sent immediately. If multiple request happen, then they happen. (Detailed synchronisation required to not have missing data).
- **Transaction Update**: Very similar to how Database transactions work, it would be possible to temporarily disable the update triggers of the elements, allowing to update several elements and when all have been changed, commit the changes which will be then delivered to the client.

**Comment by rkkoszewski** [comment]
Closing this as it has been split into real Milestones now.
